"use client"

import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Calendar, Clock, ArrowRight, ChevronDown, ChevronUp } from "lucide-react"
import { useState } from "react"

const meetings = [
  {
    id: 1,
    client: "Acme Corporation",
    date: "2024-01-15",
    duration: "45 min",
    summary:
      "Discussion about the expansion of the inventory system. The client showed interest in demand prediction modules and advanced analytics.",
    topics: ["Inventory", "Prediction", "Analytics"],
    opportunities: 2,
    period: "January 2024",
  },
  {
    id: 2,
    client: "TechStart SL",
    date: "2024-01-12",
    duration: "60 min",
    summary:
      "Quarterly project review. Needs for integration with Slack and Drive were identified to improve team workflow.",
    topics: ["Integrations", "Workflow", "Slack"],
    opportunities: 1,
    period: "January 2024",
  },
  {
    id: 3,
    client: "Global Logistics",
    date: "2024-01-10",
    duration: "30 min",
    summary:
      "Presentation of new dashboard functionalities. The client requested custom metrics and automated report export.",
    topics: ["Dashboard", "Reports", "Metrics"],
    opportunities: 3,
    period: "January 2024",
  },
]

export function MeetingSummaries() {
  const [selectedPeriod, setSelectedPeriod] = useState("Todos")
  const [expandedId, setExpandedId] = useState<number | null>(null)

  return (
    <div>
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-foreground mb-3">Meeting Summaries</h2>
        <p className="text-lg text-muted-foreground">
          Automatically generated by AI to keep your team informed
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {meetings.map((meeting) => (
          <Card
            key={meeting.id}
            className="p-8 border-border/50 hover:border-primary transition-all hover:shadow-lg hover:-translate-y-1 group cursor-pointer"
            onClick={() => setExpandedId(expandedId === meeting.id ? null : meeting.id)}
          >
            <div className="flex items-start justify-between mb-4">
              <div>
                <h3 className="text-xl font-semibold text-foreground group-hover:text-primary transition-colors mb-2">
                  {meeting.client}
                </h3>
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Calendar className="h-4 w-4" />
                    {new Date(meeting.date).toLocaleDateString("en-US", {
                      day: "numeric",
                      month: "long",
                      year: "numeric",
                    })}
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Clock className="h-4 w-4" />
                    {meeting.duration}
                  </div>
                </div>
              </div>
              {expandedId === meeting.id ? (
                <ChevronUp className="h-5 w-5 text-primary" />
              ) : (
                <ChevronDown className="h-5 w-5 text-muted-foreground group-hover:text-primary transition-all" />
              )}
            </div>

            <p className="text-base text-muted-foreground mb-4 leading-relaxed">{meeting.summary}</p>

            <div className="flex items-center justify-between pt-4 border-t border-border/50">
              <div className="flex flex-wrap gap-2">
                {meeting.topics.map((topic, idx) => (
                  <Badge key={idx} variant="secondary" className="text-sm py-1 px-3">
                    {topic}
                  </Badge>
                ))}
              </div>
              {meeting.opportunities > 0 && (
                <Badge className="text-sm py-1 px-3 bg-primary/10 text-primary border-0">
                  {meeting.opportunities} {meeting.opportunities === 1 ? "opportunity" : "opportunities"}
                </Badge>
              )}
            </div>

            {expandedId === meeting.id && (
              <div className="mt-6 pt-6 border-t border-border/50">
                <h4 className="font-semibold text-foreground mb-3">Complete meeting details</h4>
                <div className="space-y-4">
                  <div>
                    <p className="text-sm text-muted-foreground leading-relaxed">{meeting.summary}</p>
                  </div>
                  <div>
                    <h5 className="text-sm font-medium text-foreground mb-2">Participants</h5>
                    <p className="text-sm text-muted-foreground">Sales team and {meeting.client}</p>
                  </div>
                  <div>
                    <h5 className="text-sm font-medium text-foreground mb-2">Pending actions</h5>
                    <ul className="text-sm text-muted-foreground space-y-1">
                      <li>• Follow up on sent proposals</li>
                      <li>• Prepare demo of new functionalities</li>
                      <li>• Coordinate technical meeting</li>
                    </ul>
                  </div>
                </div>
              </div>
            )}
          </Card>
        ))}
      </div>
    </div>
  )
}
